-- Migration: Add Findings and Activities for Cloud Intelligence
-- These tables enable the Web Dashboard to display strategic insights without local Python execution.

-- Findings Table (Strategic Alerts)
CREATE TABLE IF NOT EXISTS public.findings (
    id TEXT PRIMARY KEY,
    project_id TEXT NOT NULL,
    type TEXT NOT NULL,
    severity TEXT NOT NULL CHECK (severity IN ('CRITICAL', 'HIGH', 'MEDIUM', 'LOW', 'INFO')),
    file_path TEXT NOT NULL,
    line_number INTEGER,
    message TEXT NOT NULL,
    recommendation TEXT,
    metadata JSONB,
    is_resolved BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    resolved_at TIMESTAMP WITH TIME ZONE,
    -- Consistency with auth
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE
);

-- Activities Table (System Logs)
CREATE TABLE IF NOT EXISTS public.activities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id TEXT NOT NULL,
    tool TEXT NOT NULL,
    action TEXT NOT NULL,
    cost_tokens INTEGER DEFAULT 0,
    tier TEXT DEFAULT 'free',
    payload JSONB,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE
);

-- Enable RLS
ALTER TABLE public.findings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.activities ENABLE ROW LEVEL SECURITY;

-- Policies for Findings
CREATE POLICY "Users can view own findings" ON public.findings
    FOR SELECT USING (auth.uid() = user_id);

-- Policies for Activities
CREATE POLICY "Users can view own activities" ON public.activities
    FOR SELECT USING (auth.uid() = user_id);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_findings_project_id ON public.findings(project_id);
CREATE INDEX IF NOT EXISTS idx_findings_severity ON public.findings(severity);
CREATE INDEX IF NOT EXISTS idx_activities_project_id ON public.activities(project_id);
CREATE INDEX IF NOT EXISTS idx_activities_created_at ON public.activities(created_at DESC);
